# server配置
server:
  port: 8080
  servlet:
    context-path: /
ip: localhost
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://${ip}:3306/TIANDI

      #      url: jdbc:mysql:///TIANDI
      username: root
      password: root123
      driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.TianHan.pojo # 配置别名
  mapper-locations: classpath:/mappers/*.xml # mapper xml位置
  configuration:  # setting配置
    auto-mapping-behavior: full
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
##jwt配置
#jwt:
#  token:
#    tokenExpiration: 120 #有效时间,单位分钟
#    tokenSignKey: headline123456  #当前程序签名秘钥 自定义